version: '3'

# networks:
#   crawler_net:
#     driver: bridge

services:
  crawler:
    build: ./
    volumes:
     - ./data:/data
    command:
      - crawl
      - --timeout
      - 10m
      - --crawler-db
      - /data/crawler.db
      # Make sure you have the GeoLite DB in the ./data directory.
      # Comment out the following two lines to disable the GeoLite DB.
      # - --geoipdb
      # - /data/GeoLite2-Country.mmdb

  api:
    build: ./
    volumes:
     - ./data:/data
    depends_on:
     - crawler
    command: "api --crawler-db /data/crawler.db --api-db /data/api.db"

  # neo4j-db:
  #   image: neo4j:latest
  #   ports:
  #     - "7474:7474" # Neo4j web interface
  #     - "7687:7687" # Neo4j Bolt protocol
  #   environment:
  #     NEO4J_AUTH: neo4j/testpassword # 设置用户名和密码
  #   volumes:
  #     - ./data:/data # 持久化数据
  #   networks:
  #     - crawler_net

  frontend:
    build: ./frontend
    volumes:
     - ./frontend/nginx.conf:/etc/nginx/conf.d/default.conf
     - ./data:/data
    depends_on:
     - api
    ports:
     - 80:80
